version: '3.8'

services:
  migrant-fe-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: 10.6.0.157:30000/migrant-fe-portal:v0.0.1
    container_name: migrant-fe-portal
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
      - PORT=3100
      - HOST=0.0.0.0
      - API_ENDPOINT=http://10.6.0.164:30033
    networks:
      - migrant-network

networks:
  migrant-network:
    driver: bridge
